export const GOVERNMENT = {
    REPUBLIC: "REPUBLIC",
    FEUDAL: "FEUDAL",
};

export const KINGDOM_NAMES = {
    ENGLAND: "ENGLAND",
    FRANCE: "FRANCE",
    HRE: "HRE",
    HUNGARY: "HUNGARY",
    BYZANTIUM: "BYZANTIUM",
    PORTUGAL: "PORTUGAL",
    ARAGON: "ARAGON",
    PAPAL_STATES: "PAPAL_STATES",
    OTTOMAN: "OTTOMAN",
    MAMLUK: "MAMLUK",
};

export const COUNTRY_CODES = {
    ENGLAND: "EN",
    FRANCE: "FR",
    HRE: "HRE",
    PORTUGAL: "PT",
    ARAGON: "AR",
    PAPAL_STATES: "PS",
    HUNGARY: "HU",
    BYZANTIUM: "BY",
    OTTOMAN: "OT",
    MAMLUK: "ML",
};

export const CITY_NAMES = {
    LONDON: "LONDON",
    BORDEAUX: "BORDEAUX",
    BRUGES: "BRUGES",
    PARIS: "PARIS",
    LYON: "LYON",
    LUBECK: "LUBECK",
    NOVGOROD: "NOVGOROD",
    NURNBERG: "NURNBERG",
    VIENNA: "VIENNA",
    BUDA: "BUDA",
    VARNA: "VARNA",
    TANA: "TANA",
    CAFFA: "CAFFA",
    TREBIZOND: "TREBIZOND",
    TOLEDO: "TOLEDO",
    GRANADA: "GRANADA",
    SPICE_ISLANDS: "SPICE_ISLANDS",
    VALENCIA: "VALENCIA",
    ALGIERS: "ALGIERS",
    PAPAL_STATES: "PAPAL_STATES",
    TIMBUKTU: "TIMBUKTU",
    VENICE: "VENICE",
    VENICE_2: "VENICE_2", // some cards allow to have 2 knights in Venice
    CONSTANTINOPLE: "CONSTANTINOPLE",
    CONSTANTINOPLE_2: "CONSTANTINOPLE_2",
    CONSTANTINOPLE_3: "CONSTANTINOPLE_3",
    MODON: "MODON",
    RHODES: "RHODES",
    CYPRUS: "CYPRUS",
    CAIRO: "CAIRO",
    RED_SEA: "RED_SEA",
};

export const REGION = {
    EAST: "EAST",
    WEST: "WEST",
};

export const RELIGION = {
    SECULAR: "SECULAR",
    CATHOLIC: "CATHOLIC",
    MUSLIM: "MUSLIM",
    REFORMIST: "REFORMIST",
};

export const VICTORY_TYPE = {
    RENAISSANCE: "RENAISSANCE",
    GLOBALIZATION: "GLOBALIZATION",
    IMPERIAL: "IMPERIAL",
    HOLY: "HOLY",
    PATRONAGE: "PATRONAGE",
};

export const CARD_TYPE = {
    VICTORY: "VICTORY",
    KINGDOM: "KINGDOM",
    PIECE: "PIECE",
    MARKET_CARD: "MARKET_CARD",
    BORDER: "BORDER",
    PIRATE: "PIRATE",
    EMPIRE: "EMPIRE",
};

export const PIECE_TYPE = {
    CATHOLIC_ROOK: "CATHOLIC_ROOK",
    MUSLIM_ROOK: "MUSLIM_ROOK",
    REFORMIST_ROOK: "REFORMIST_ROOK",
    CATHOLIC_ROOK_FREE: "CATHOLIC_ROOK_FREE",
    MUSLIM_ROOK_FREE: "MUSLIM_ROOK_FREE",
    REFORMIST_ROOK_FREE: "REFORMIST_ROOK_FREE",
    CATHOLIC_KNIGHT: "CATHOLIC_KNIGHT",
    MUSLIM_KNIGHT: "MUSLIM_KNIGHT",
    REFORMIST_KNIGHT: "REFORMIST_KNIGHT",
    CATHOLIC_KNIGHT_FREE: "CATHOLIC_KNIGHT_FREE",
    MUSLIM_KNIGHT_FREE: "MUSLIM_KNIGHT_FREE",
    REFORMIST_KNIGHT_FREE: "REFORMIST_KNIGHT_FREE",
    CATHOLIC_BISHOP: "CATHOLIC_BISHOP",
    MUSLIM_BISHOP: "MUSLIM_BISHOP",
    REFORMIST_BISHOP: "REFORMIST_BISHOP",
};

export const CARD_POSITION = {
    VERTICAL: "VERTICAL",
    HORIZONTAL: "HORIZONTAL",
    SIDE: "SIDE",
    TOP: "TOP",
    EMPTY: "EMPTY",
};

export const BANKERS = {
    FUGGER: "Fugger",
    MARCHIONNI: "Marchionni",
    COEUR: "Coeur",
    MEDICI: "Medici",
};

export const DOCUMENTATION = {
    OPERATIONS: "OPERATIONS",
    BATTLE_TABLE: "BATTLE_TABLE",
};